on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 8
          os: ubuntu-latest
        - java: 17
          os: windows-latest
        - java: 21
          os: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: sbt/setup-sbt@v1
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - run: sbt -v scalafmtSbtCheck scalafmtCheckAll test publishLocal pluginJVM2_12/scripted
